info:
  description: توثيق API للمشروع التجريبي الذي يربط 10 محافظ يمنية.
  title: بنك الزبيري API
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/wallets:
    get:
      responses:
        '200':
          content:
            application/json:
              example:
              - code: JIB
                name: جيب
              - code: ONECASH
                name: ون كاش
          description: قائمة المحافظ اليمنية المدعومة
      summary: قائمة المحافظ
  /api/wallets/confirm:
    post:
      requestBody:
        content:
          application/json:
            example:
              otp: '1234'
              phone: +9677XXXXXXX
              provider: JIB
            schema:
              properties:
                otp:
                  type: string
                phone:
                  type: string
                provider:
                  type: string
              required:
              - provider
              - phone
              - otp
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                message: تم ربط المحفظة JIB بالرقم +9677XXXXXXX
                ok: true
          description: تم ربط المحفظة
      summary: تأكيد ربط المحفظة
  /api/wallets/link:
    post:
      requestBody:
        content:
          application/json:
            example:
              phone: +9677XXXXXXX
              provider: JIB
            schema:
              properties:
                phone:
                  type: string
                provider:
                  type: string
              required:
              - provider
              - phone
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                message: تم ارسال رمز التحقق إلى +9677XXXXXXX عبر JIB
                ok: true
          description: تم إرسال رمز التحقق
      summary: ربط محفظة - إرسال رمز تحقق
